package dao.mapper;

import dao.model.Good;
import dao.model.GoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    long countByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int deleteByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    List<Good> selectByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    Good selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int updateByExample(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_good
     *
     * @mbg.generated Wed Jun 06 14:26:34 CST 2018
     */
    int updateByPrimaryKey(Good record);

    /**
    * @mbg.generated
    */
    List<Long> selectPrimaryKeyByExample(GoodExample example);

    /**
    * @mbg.generated
    */
    List<Long> selectPrimaryKeyLimitedByExample(@Param("offset") Long offset, @Param("num") Long num, @Param("example") GoodExample example);
}