package io.github.geniusv.dao.mapper;

import io.github.geniusv.dao.model.Order;
import io.github.geniusv.dao.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_order
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByPrimaryKey(Order record);

    /**
    * @mbg.generated
    */
    List<Long> selectPrimaryKeyByExample(OrderExample example);

    /**
    * @mbg.generated
    */
    List<Long> selectPrimaryKeyLimitedByExample(@Param("offset") Long offset, @Param("num") Long num, @Param("example") OrderExample example);
}