package io.github.geniusv.dao.mapper;

import io.github.geniusv.dao.model.Role;
import io.github.geniusv.dao.model.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_role
     *
     * @mbg.generated Wed Jun 06 14:51:00 CST 2018
     */
    int updateByPrimaryKey(Role record);

    /**
    * @mbg.generated
    */
    List<Long> selectPrimaryKeyByExample(RoleExample example);

    /**
    * @mbg.generated
    */
    List<Long> selectPrimaryKeyLimitedByExample(@Param("offset") Long offset, @Param("num") Long num, @Param("example") RoleExample example);
}