package io.github.geniusv.dao.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.id
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.user_name
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.password
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.status
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.email
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.tel
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.gender
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_user
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.id
     *
     * @return the value of v_user.id
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.id
     *
     * @param id the value for v_user.id
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.user_name
     *
     * @return the value of v_user.user_name
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.user_name
     *
     * @param userName the value for v_user.user_name
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.password
     *
     * @return the value of v_user.password
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.password
     *
     * @param password the value for v_user.password
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.status
     *
     * @return the value of v_user.status
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.status
     *
     * @param status the value for v_user.status
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.email
     *
     * @return the value of v_user.email
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.email
     *
     * @param email the value for v_user.email
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.tel
     *
     * @return the value of v_user.tel
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.tel
     *
     * @param tel the value for v_user.tel
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.gender
     *
     * @return the value of v_user.gender
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.gender
     *
     * @param gender the value for v_user.gender
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Sat Jun 09 23:54:42 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", status=").append(status);
        sb.append(", email=").append(email);
        sb.append(", tel=").append(tel);
        sb.append(", gender=").append(gender);
        sb.append("]");
        return sb.toString();
    }
}